#!/bin/bash

# Quick reference for Claude Code n8n operations
echo "🔧 n8n API Tools for Claude Code"
echo "================================"
echo ""
echo "💡 All commands return JSON that can be piped to jq for parsing"
echo ""
echo "📋 WORKFLOW OPERATIONS:"
echo "  scripts/n8n-api.sh list-workflows              # List all workflows"
echo "  scripts/n8n-api.sh get-workflow [id]           # Get workflow details"
echo "  scripts/n8n-api.sh create-workflow [file]      # Create from JSON file"
echo "  scripts/n8n-api.sh update-workflow [id] [file] # Update existing"
echo "  scripts/n8n-api.sh delete-workflow [id]        # Delete workflow"
echo "  scripts/n8n-api.sh activate-workflow [id]      # Activate for execution"
echo "  scripts/n8n-api.sh deactivate-workflow [id]    # Deactivate"
echo ""
echo "📊 EXECUTION OPERATIONS:"
echo "  scripts/n8n-api.sh list-executions [id]       # List executions (optional workflow-id)"
echo "  scripts/n8n-api.sh get-execution [id]         # Get execution details"
echo ""
echo "🔐 CREDENTIAL OPERATIONS:"
echo "  scripts/n8n-api.sh list-credentials          # List all credentials"
echo "  scripts/n8n-api.sh get-credential [id]       # Get credential details"
echo "  scripts/n8n-api.sh create-credential [file]  # Create from JSON file"
echo "  scripts/n8n-api.sh test-credential [id]      # Test connection"
echo ""
echo "🔧 UTILITY OPERATIONS:"
echo "  scripts/n8n-api.sh get-workflow-status [id]  # Get workflow status"
echo "  scripts/n8n-api.sh raw [method] [endpoint] [data] # Direct API call"
echo ""
echo "📖 EXAMPLES:"
echo "  # Get all workflows and extract names"
echo "  scripts/n8n-api.sh list-workflows | jq '.data[].name'"
echo ""
echo "  # Create workflow and get its ID"
echo "  scripts/n8n-api.sh create-workflow my.json | jq '.id'"
echo ""
echo "  # Check if workflow is active"
echo "  scripts/n8n-api.sh get-workflow ABC123 | jq '.active'"
echo ""
echo "🎯 COMMON PATTERNS:"
echo "  # List inactive workflows"
echo "  scripts/n8n-api.sh list-workflows | jq '.data[] | select(.active == false) | .name'"
echo ""
echo "  # Get workflow execution count"
echo "  scripts/n8n-api.sh list-executions WORKFLOW_ID | jq '.data | length'"